// ============================================================
// ARENA LINKS — every link a desk can drop into a slide deck (BK, 2026-10-05 22:32:
// "make sure that each desk gets to reference those map links when they're building their
// slide decks...same goes for any reference to arena tools...like Doc Assist, Atlas, any
// future writing tools or otherwise").
//
// Reads what is in public/ (what a push makes live) and writes:
//   arena-links.json  — for the desks' deck builders (look a link up by unit, casefile, doc or map id)
//   arena-links.md    — the same list for a person
// Josh regenerates it at every push and copies it to flashpoint OUTPUTS/arena-links/.
// The scheme is deeplinks.js; a link never carries anything about a student.
// Usage: node scripts/links.mjs <out-dir>
// ============================================================
import fs from 'node:fs'
import path from 'node:path'

const BASE = 'https://thearena.flashpointhistory.com/'
const PUB = path.resolve('public')
const read = f => { try { return JSON.parse(fs.readFileSync(path.join(PUB, f), 'utf8')) } catch { return null } }
const ref = r => String(r || '').replace(/^content\//, 'content/')
const KEY = { us11r: 'us', global10r: 'global' }
const out = process.argv[2] || 'links-out'

const m = read('arena.manifest.json')
const L = { _README: "Every live Arena link, by course and unit. Built by Josh from what is live (scripts/links.mjs); regenerated at every push. Link ids never change: map ids, unit numbers, casefile letters and document numbers are stable. Nothing in a link points at a student.",
  base: BASE, courses: {} }
const md = ['# Arena links', '', '_Every live Arena link, for slide decks and Classroom posts. Regenerated by Josh at every push._', '']

for (const c of m.courses || []) {
  const k = KEY[c.id] || c.id
  const C = { label: c.label, door: `${BASE}#/${k}`, lanes: {}, units: {} }
  md.push(`## ${c.label}`, '', `- The door: ${C.door}`)
  if (c.unit0?.published) { C.unit0 = `${BASE}#/${k}/0`; md.push(`- Unit 0, the six skills: ${C.unit0}`) }
  if ((c.threads || []).some(t => t.published)) { C.lanes.threads = `${BASE}#/${k}/threads`; md.push(`- Threads map: ${C.lanes.threads}`) }
  if ((c.issues || []).some(t => t.published)) { C.lanes.issues = `${BASE}#/${k}/issues`; md.push(`- Enduring Issues map: ${C.lanes.issues}`) }
  const atlasFiles = (c.atlas || []).filter(a => a.published).map(a => read(ref(a.content_ref))).filter(Boolean)
  const maps = atlasFiles.flatMap(f => f.maps || []).filter(x => x.status === 'open')
  if ((c.atlas || []).some(a => a.published)) { C.lanes.atlas = `${BASE}#/${k}/atlas`; md.push(`- Atlas: ${C.lanes.atlas}`) }
  // A set that ships ahead is listed with its open day, so a deck built now can carry its link.
  const wl = (c.writing_lab || []).filter(e => e.published)
  if (wl.length) { C.lanes.writing_lab = `${BASE}#/${k}/writing-lab`; md.push(`- Writing Lab: ${C.lanes.writing_lab}`) }
  md.push('')
  for (const u of c.units || []) {
    if (u.published !== true) continue
    const n = String(u.number)
    const U = { name: u.label, room: `${BASE}#/${k}/${n}` }
    md.push(`### ${String(u.label).startsWith(n) ? u.label : `${n} · ${u.label}`}`, '', `- The room: ${U.room}`)
    if (u.brief_ref) { U.review = `${BASE}#/${k}/${n}/review`; md.push(`- Unit review: ${U.review}`) }
    if (u.doc_assist?.published) {
      const pack = read(ref(u.doc_assist.content_ref))
      U.doc_assist = { link: `${BASE}#/${k}/${n}/doc-assist`, casefiles: {} }
      md.push(`- Doc Assist: ${U.doc_assist.link}`)
      for (const cf of (pack?.casefiles || []).filter(x => x.status === 'open' && (x.docs || []).length)) {
        const CF = { link: `${BASE}#/${k}/${n}/doc-assist/${cf.id}`, docs: {} }
        md.push(`  - Casefile ${cf.id}: ${CF.link}`)
        for (const d of cf.docs) {
          CF.docs[d.n] = { title: d.title, link: `${BASE}#/${k}/${n}/doc-assist/${cf.id}/${d.n}` }
          md.push(`    - Document ${d.n}, ${d.title}: ${CF.docs[d.n].link}`)
        }
        U.doc_assist.casefiles[cf.id] = CF
      }
    }
    const um = maps.filter(x => String(x.unit) === n)
    if (um.length) {
      U.atlas = { link: `${BASE}#/${k}/${n}/atlas`, maps: {} }
      md.push(`- ${n} Atlas: ${U.atlas.link}`)
      for (const x of um) {
        U.atlas.maps[x.id] = { title: x.title, casefile: x.casefile, link: `${BASE}#/${k}/atlas/${encodeURIComponent(x.id)}` }
        md.push(`  - ${x.id} · ${x.title}: ${U.atlas.maps[x.id].link}`)
      }
    }
    const ws = wl.filter(e => String(e.unit) === n)
    if (ws.length) {
      U.writing_lab = {}
      for (const e of ws) {
        const d = read(ref(e.content_ref))
        U.writing_lab[e.slug] = { title: `${d?.name || e.tool} · Set ${e.set ?? 1} · ${d?.set_title || ''}`, casefile: e.casefile, opens_on: e.opens_on || null, link: `${BASE}#/${k}/writing-lab/${e.slug}` }
        md.push(`- Writing Lab, ${U.writing_lab[e.slug].title}${e.opens_on ? ` (opens ${e.opens_on})` : ''}: ${U.writing_lab[e.slug].link}`)
      }
    }
    C.units[n] = U
    md.push('')
  }
  L.courses[k] = C
}
if (m.office?.published) { L.office = `${BASE}#/office`; md.push(`## BK's Office`, '', `- ${L.office}`, '') }

fs.mkdirSync(out, { recursive: true })
fs.writeFileSync(path.join(out, 'arena-links.json'), JSON.stringify(L, null, 2) + '\n')
fs.writeFileSync(path.join(out, 'arena-links.md'), md.join('\n') + '\n')
const count = (JSON.stringify(L).match(/https:\/\//g) || []).length
console.log(`arena-links: ${count} links written to ${out}/`)
